### ISSUE TITLE
ERROR: crashed when deployed to heroku.

### ISSUE THREAD

**Issue by 25** [sbkwgh/forum#16]
```
2019-01-11T03:09:54.056939+00:00 app[web.1]: 
2019-01-11T03:09:54.059075+00:00 app[web.1]: Sequelize CLI [Node: 11.6.0, CLI: 4.1.1, ORM: 3.33.0]
2019-01-11T03:09:54.059176+00:00 app[web.1]: 
2019-01-11T03:09:54.074078+00:00 app[web.1]: Loaded configuration file "config/config.json".
2019-01-11T03:09:54.074197+00:00 app[web.1]: Using environment "production".
2019-01-11T03:09:54.098279+00:00 app[web.1]: 
2019-01-11T03:09:54.098516+00:00 app[web.1]: ERROR: Please install 'pg' module manually
2019-01-11T03:09:54.098573+00:00 app[web.1]: 
2019-01-11T03:09:54.107929+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2019-01-11T03:09:54.108315+00:00 app[web.1]: npm ERR! errno 1
2019-01-11T03:09:54.110059+00:00 app[web.1]: npm ERR! backend@0.0.0 start: `sequelize db:migrate && node server.js`
2019-01-11T03:09:54.110249+00:00 app[web.1]: npm ERR! Exit status 1
2019-01-11T03:09:54.110556+00:00 app[web.1]: npm ERR!
2019-01-11T03:09:54.110743+00:00 app[web.1]: npm ERR! Failed at the backend@0.0.0 start script.
2019-01-11T03:09:54.110854+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

After I installed pg using `npm install pg`, I got this error:

```
2019-01-11T03:12:53.117703+00:00 heroku[web.1]: Starting process with command `npm run start`
2019-01-11T03:12:56.489218+00:00 app[web.1]: 
2019-01-11T03:12:56.489243+00:00 app[web.1]: > backend@0.0.0 start /app
2019-01-11T03:12:56.489245+00:00 app[web.1]: > sequelize db:migrate && node server.js
2019-01-11T03:12:56.489247+00:00 app[web.1]: 
2019-01-11T03:12:57.818867+00:00 app[web.1]: /app/node_modules/pg/lib/connection.js:120
2019-01-11T03:12:57.818879+00:00 app[web.1]: var eventName = msg.name === 'error' ? 'errorMessage' : msg.name
2019-01-11T03:12:57.818885+00:00 app[web.1]: ^
2019-01-11T03:12:57.818887+00:00 app[web.1]: 
2019-01-11T03:12:57.818889+00:00 app[web.1]: TypeError: Cannot read property 'name' of undefined
2019-01-11T03:12:57.818890+00:00 app[web.1]: at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:120:27)
2019-01-11T03:12:57.818892+00:00 app[web.1]: at Socket.emit (events.js:188:13)
2019-01-11T03:12:57.818894+00:00 app[web.1]: at addChunk (_stream_readable.js:288:12)
2019-01-11T03:12:57.818896+00:00 app[web.1]: at readableAddChunk (_stream_readable.js:269:11)
2019-01-11T03:12:57.818898+00:00 app[web.1]: at Socket.Readable.push (_stream_readable.js:224:10)
2019-01-11T03:12:57.818899+00:00 app[web.1]: at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
2019-01-11T03:12:57.851410+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2019-01-11T03:12:57.852136+00:00 app[web.1]: npm ERR! errno 1
2019-01-11T03:12:57.854781+00:00 app[web.1]: npm ERR! backend@0.0.0 start: `sequelize db:migrate && node server.js`
2019-01-11T03:12:57.855264+00:00 app[web.1]: npm ERR! Exit status 1
2019-01-11T03:12:57.855972+00:00 app[web.1]: npm ERR!
2019-01-11T03:12:57.856328+00:00 app[web.1]: npm ERR! Failed at the backend@0.0.0 start script.
```

**Comment by 25** [comment]
I switched my DB to mysql.

However, it is spamming errors.

```
2019-01-11T04:27:49.865613+00:00 app[web.1]: { SequelizeDatabaseError: ER_NO_SUCH_TABLE: Table 'forum_prod.Sessions' doesn't exist
2019-01-11T04:27:49.865616+00:00 app[web.1]: at Query.formatError (/app/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
2019-01-11T04:27:49.865618+00:00 app[web.1]: at Query._callback (/app/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
2019-01-11T04:27:49.865619+00:00 app[web.1]: at Query.Sequence.end (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
2019-01-11T04:27:49.865621+00:00 app[web.1]: at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
2019-01-11T04:27:49.865623+00:00 app[web.1]: at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:279:23)
2019-01-11T04:27:49.865625+00:00 app[web.1]: at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:76:12)
2019-01-11T04:27:49.865626+00:00 app[web.1]: at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:39:16)
2019-01-11T04:27:49.865628+00:00 app[web.1]: at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:103:28)
2019-01-11T04:27:49.865630+00:00 app[web.1]: at Socket.emit (events.js:188:13)
2019-01-11T04:27:49.865631+00:00 app[web.1]: at addChunk (_stream_readable.js:288:12)
2019-01-11T04:27:49.865633+00:00 app[web.1]: at readableAddChunk (_stream_readable.js:269:11)
2019-01-11T04:27:49.865635+00:00 app[web.1]: at Socket.Readable.push (_stream_readable.js:224:10)
2019-01-11T04:27:49.865639+00:00 app[web.1]: at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
2019-01-11T04:27:49.865641+00:00 app[web.1]: name: 'SequelizeDatabaseError',
2019-01-11T04:27:49.865642+00:00 app[web.1]: message:
2019-01-11T04:27:49.865644+00:00 app[web.1]: "ER_NO_SUCH_TABLE: Table 'forum_prod.Sessions' doesn't exist",
2019-01-11T04:27:49.865646+00:00 app[web.1]: parent:
2019-01-11T04:27:49.865647+00:00 app[web.1]: { Error: ER_NO_SUCH_TABLE: Table 'forum_prod.Sessions' doesn't exist
2019-01-11T04:27:49.865649+00:00 app[web.1]: at Query.Sequence._packetToError (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
2019-01-11T04:27:49.865651+00:00 app[web.1]: at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
2019-01-11T04:27:49.865653+00:00 app[web.1]: at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:279:23)
2019-01-11T04:27:49.865654+00:00 app[web.1]: at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:76:12)
2019-01-11T04:27:49.865656+00:00 app[web.1]: at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:39:16)
2019-01-11T04:27:49.865657+00:00 app[web.1]: at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:103:28)
2019-01-11T04:27:49.865659+00:00 app[web.1]: at Socket.emit (events.js:188:13)
2019-01-11T04:27:49.865660+00:00 app[web.1]: at addChunk (_stream_readable.js:288:12)
2019-01-11T04:27:49.865662+00:00 app[web.1]: at readableAddChunk (_stream_readable.js:269:11)
2019-01-11T04:27:49.865664+00:00 app[web.1]: at Socket.Readable.push (_stream_readable.js:224:10)
2019-01-11T04:27:49.865665+00:00 app[web.1]: at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
2019-01-11T04:27:49.865667+00:00 app[web.1]: --------------------
2019-01-11T04:27:49.865669+00:00 app[web.1]: at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:145:48)
2019-01-11T04:27:49.865670+00:00 app[web.1]: at Connection.query (/app/node_modules/mysql/lib/Connection.js:208:25)
2019-01-11T04:27:49.865672+00:00 app[web.1]: at /app/node_modules/sequelize/lib/dialects/mysql/query.js:40:21
2019-01-11T04:27:49.865673+00:00 app[web.1]: at Promise._execute (/app/node_modules/bluebird/js/release/debuggability.js:313:9)
2019-01-11T04:27:49.865675+00:00 app[web.1]: at Promise._resolveFromExecutor (/app/node_modules/bluebird/js/release/promise.js:483:18)
2019-01-11T04:27:49.865677+00:00 app[web.1]: at new Promise (/app/node_modules/bluebird/js/release/promise.js:79:10)
2019-01-11T04:27:49.865685+00:00 app[web.1]: at Query.run (/app/node_modules/sequelize/lib/dialects/mysql/query.js:39:17)
2019-01-11T04:27:49.865687+00:00 app[web.1]: at /app/node_modules/sequelize/lib/sequelize.js:849:20
2019-01-11T04:27:49.865689+00:00 app[web.1]: at /app/node_modules/retry-as-promised/index.js:39:21
2019-01-11T04:27:49.865690+00:00 app[web.1]: at Promise._execute (/app/node_modules/bluebird/js/release/debuggability.js:313:9)
2019-01-11T04:27:49.865692+00:00 app[web.1]: at Promise._resolveFromExecutor (/app/node_modules/bluebird/js/release/promise.js:483:18)
2019-01-11T04:27:49.865693+00:00 app[web.1]: at new Promise (/app/node_modules/bluebird/js/release/promise.js:79:10)
2019-01-11T04:27:49.865695+00:00 app[web.1]: at retryAsPromised (/app/node_modules/retry-as-promised/index.js:29:10)
2019-01-11T04:27:49.865697+00:00 app[web.1]: at /app/node_modules/sequelize/lib/sequelize.js:848:12
2019-01-11T04:27:49.865698+00:00 app[web.1]: at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
2019-01-11T04:27:49.865700+00:00 app[web.1]: at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
2019-01-11T04:27:49.865701+00:00 app[web.1]: code: 'ER_NO_SUCH_TABLE',
2019-01-11T04:27:49.865703+00:00 app[web.1]: errno: 1146,
2019-01-11T04:27:49.865704+00:00 app[web.1]: sqlMessage: "Table 'forum_prod.Sessions' doesn't exist",
2019-01-11T04:27:49.865706+00:00 app[web.1]: sqlState: '42S02',
2019-01-11T04:27:49.865708+00:00 app[web.1]: index: 0,
2019-01-11T04:27:49.865709+00:00 app[web.1]: sql:
2019-01-11T04:27:49.865711+00:00 app[web.1]: "SELECT `sid`, `expires`, `data`, `createdAt`, `updatedAt` FROM `Sessions` AS `Session` WHERE `Session`.`sid` = '0h9rrTWcZrV3KxkEKZCoII9512gdetVW';" },
2019-01-11T04:27:49.865713+00:00 app[web.1]: original:
2019-01-11T04:27:49.865714+00:00 app[web.1]: { Error: ER_NO_SUCH_TABLE: Table 'forum_prod.Sessions' doesn't exist
2019-01-11T04:27:49.865716+00:00 app[web.1]: at Query.Sequence._packetToError (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
2019-01-11T04:27:49.865717+00:00 app[web.1]: at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
2019-01-11T04:27:49.865719+00:00 app[web.1]: at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:279:23)
2019-01-11T04:27:49.865727+00:00 app[web.1]: at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:76:12)
2019-01-11T04:27:49.865729+00:00 app[web.1]: at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:39:16)
2019-01-11T04:27:49.865731+00:00 app[web.1]: at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:103:28)
2019-01-11T04:27:49.865733+00:00 app[web.1]: at Socket.emit (events.js:188:13)
2019-01-11T04:27:49.865734+00:00 app[web.1]: at addChunk (_stream_readable.js:288:12)
2019-01-11T04:27:49.865736+00:00 app[web.1]: at readableAddChunk (_stream_readable.js:269:11)
2019-01-11T04:27:49.865737+00:00 app[web.1]: at Socket.Readable.push (_stream_readable.js:224:10)
2019-01-11T04:27:49.865739+00:00 app[web.1]: at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
2019-01-11T04:27:49.865741+00:00 app[web.1]: --------------------
2019-01-11T04:27:49.865742+00:00 app[web.1]: at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:145:48)
2019-01-11T04:27:49.865744+00:00 app[web.1]: at Connection.query (/app/node_modules/mysql/lib/Connection.js:208:25)
2019-01-11T04:27:49.865745+00:00 app[web.1]: at /app/node_modules/sequelize/lib/dialects/mysql/query.js:40:21
2019-01-11T04:27:49.865747+00:00 app[web.1]: at Promise._execute (/app/node_modules/bluebird/js/release/debuggability.js:313:9)
2019-01-11T04:27:49.865749+00:00 app[web.1]: at Promise._resolveFromExecutor (/app/node_modules/bluebird/js/release/promise.js:483:18)
2019-01-11T04:27:49.865750+00:00 app[web.1]: at new Promise (/app/node_modules/bluebird/js/release/promise.js:79:10)
2019-01-11T04:27:49.865752+00:00 app[web.1]: at Query.run (/app/node_modules/sequelize/lib/dialects/mysql/query.js:39:17)
2019-01-11T04:27:49.865753+00:00 app[web.1]: at /app/node_modules/sequelize/lib/sequelize.js:849:20
2019-01-11T04:27:49.865755+00:00 app[web.1]: at /app/node_modules/retry-as-promised/index.js:39:21
2019-01-11T04:27:49.865757+00:00 app[web.1]: at Promise._execute (/app/node_modules/bluebird/js/release/debuggability.js:313:9)
2019-01-11T04:27:49.865758+00:00 app[web.1]: at Promise._resolveFromExecutor (/app/node_modules/bluebird/js/release/promise.js:483:18)
2019-01-11T04:27:49.865760+00:00 app[web.1]: at new Promise (/app/node_modules/bluebird/js/release/promise.js:79:10)
2019-01-11T04:27:49.865761+00:00 app[web.1]: at retryAsPromised (/app/node_modules/retry-as-promised/index.js:29:10)
2019-01-11T04:27:49.865763+00:00 app[web.1]: at /app/node_modules/sequelize/lib/sequelize.js:848:12
2019-01-11T04:27:49.865765+00:00 app[web.1]: at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
2019-01-11T04:27:49.865766+00:00 app[web.1]: at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
```
I checked the db and the tables are created:

![mysql](https://user-images.githubusercontent.com/31719556/51013327-d56f5400-152f-11e9-8f8f-b99a6a78c476.png)

**Comment by 25** [comment]
Ok, I found a way to get around this issue:
`Database and table names are not case sensitive in Windows, and case sensitive in most varieties of Unix.`
I was Debian as my MySQL server, and when I switched to windows it worked like a charm.
