### ISSUE TITLE
SequelizeDatabaseError : Sessions' doesn't exist

### ISSUE THREAD

**Issue by tsn361** [sbkwgh/forum#20]
Hi,

I am trying to run the code in a Ubuntu 18 machine.
When I run "npm run dev" it's migrating DB perfectly (see table list in attached image). 

but when front-end making API call, I am getting the error below: 

{ SequelizeDatabaseError: ER_NO_SUCH_TABLE: Table 'forum_dev.Sessions' doesn't exist
    at Query.formatError (/var/www/html/forum/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
    at Query.<anonymous> (/var/www/html/forum/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query.<anonymous> (/var/www/html/forum/node_modules/mysql/lib/Connection.js:525:10)
    at Query._callback (/var/www/html/forum/node_modules/mysql/lib/Connection.js:491:16)
    at Query.Sequence.end (/var/www/html/forum/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/var/www/html/forum/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
    at Protocol._parsePacket (/var/www/html/forum/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/var/www/html/forum/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/var/www/html/forum/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/var/www/html/forum/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/var/www/html/forum/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/var/www/html/forum/node_modules/mysql/lib/Connection.js:525:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
  name: 'SequelizeDatabaseError',
  message: 'ER_NO_SUCH_TABLE: Table \'forum_dev.Sessions\' doesn\'t exist',
  parent: 
   { Error: ER_NO_SUCH_TABLE: Table 'forum_dev.Sessions' doesn't exist

DB table list after migration:
![froum-db](https://user-images.githubusercontent.com/12516760/67278574-10ed7480-f4eb-11e9-884e-dce3c1eddbfb.png)

any idea how to fix it?
Thanks in advance.

**Comment by mzch** [comment]
Perhaps, this is similar to my issue, #23 . If possible, you'd add `lower_case_table_names  = 1` at `[mysqld]` section in my.cnf.
