### ISSUE TITLE
my build is failing

### ISSUE THREAD

**Issue by Wolfleader101** [sbkwgh/forum#28]
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  >= 7.6.0
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version >= 7.6.0...
       Downloading and installing node 14.1.0...
       Using default npm version: 6.14.4
       
-----> Installing dependencies
       Installing node modules (package.json + package-lock)
       
       > sharp@0.22.1 install /tmp/build_f8034bdfe140842ee7dc2053226e76c7/node_modules/sharp
       > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
       
       info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.4/libvips-8.7.4-linux-x64.tar.gz
       make: Entering directory '/tmp/build_f8034bdfe140842ee7dc2053226e76c7/node_modules/sharp/build'
         TOUCH Release/obj.target/libvips-cpp.stamp
         CXX(target) Release/obj.target/sharp/src/common.o
         CXX(target) Release/obj.target/sharp/src/metadata.o
         CXX(target) Release/obj.target/sharp/src/stats.o
       ../src/stats.cc: In member function ‘virtual void StatsWorker::HandleOKCallback()’:
       ../src/stats.cc:130:37: error: no matching function for call to ‘v8::Array::Set(int&, v8::Local<v8::Object>&)’
                channels->Set(i, channelStat);
                                            ^
       In file included from /app/.cache/node-gyp/14.1.0/include/node/node.h:67:0,
                        from ../src/stats.cc:19:
       /app/.cache/node-gyp/14.1.0/include/node/v8.h:3639:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
          V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                            ^~~
       /app/.cache/node-gyp/14.1.0/include/node/v8.h:3639:37: note:   candidate expects 3 arguments, 2 provided
       /app/.cache/node-gyp/14.1.0/include/node/v8.h:3642:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
          V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                            ^~~
       /app/.cache/node-gyp/14.1.0/include/node/v8.h:3642:37: note:   candidate expects 3 arguments, 2 provided
       At global scope:
       cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
       sharp.target.mk:138: recipe for target 'Release/obj.target/sharp/src/stats.o' failed
       make: *** [Release/obj.target/sharp/src/stats.o] Error 1
       make: Leaving directory '/tmp/build_f8034bdfe140842ee7dc2053226e76c7/node_modules/sharp/build'
       gyp ERR! build error 
       gyp ERR! stack Error: `make` failed with exit code: 2
       gyp ERR! stack     at ChildProcess.onExit (/tmp/build_f8034bdfe140842ee7dc2053226e76c7/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
       gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
       gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
       gyp ERR! System Linux 4.4.0-1062-aws
       gyp ERR! command "/tmp/build_f8034bdfe140842ee7dc2053226e76c7/.heroku/node/bin/node" "/tmp/build_f8034bdfe140842ee7dc2053226e76c7/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
       gyp ERR! cwd /tmp/build_f8034bdfe140842ee7dc2053226e76c7/node_modules/sharp
       gyp ERR! node -v v14.1.0
       gyp ERR! node-gyp -v v5.1.0
       gyp ERR! not ok 
       npm ERR! code ELIFECYCLE
       npm ERR! errno 1
       npm ERR! sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
       npm ERR! Exit status 1
       npm ERR! 
       npm ERR! Failed at the sharp@0.22.1 install script.
       npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.6nihD/_logs/2020-05-04T11_01_15_492Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Dangerous semver range (>) in engines.node
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

**Comment by mzch** [comment]
Vue Forum is compatible with only v8.x or earlier. Try ndenv or nvm.

**Comment by Wolfleader101** [comment]
oh ok how would i use nvm instead?

**Comment by mzch** [comment]
Personally I recomend ndenv...but ok, please see https://github.com/nvm-sh/nvm

**Comment by mzch** [comment]
The latest need `v10.x`

**Comment by joflink** [comment]
change the engines in the main package.json like to this 

"engines": { "node": "10.x" },
